/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zcpkovhwatmvippszdwa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjcGtvdmh3YXRtdmlwcHN6ZHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODIxMzIsImV4cCI6MjA3Mzc1ODEzMn0.WLFRP3CxrDcoNLwHEOUcLMKbaFAtnceqkktDyNlQxKM"

export const isSupabaseConfigured = () => {
  return projectId && projectId !== "your-project-id" && 
         publicAnonKey && publicAnonKey !== "your-anon-key";
}