export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  description: string;
  requirements: string[];
  postedDate: string;
  deadline: string;
  salary: string;
  type: 'mega_job' | 'premium_job' | 'prime_job' | 'latest_job' | 'newspaper_job';
  tier: 'mega_job' | 'premium_job' | 'prime_job' | 'latest_job' | 'newspaper_job' | 'megajob' | 'premium' | 'prime' | 'latest' | 'newspaper';
  category: string;
  experience: string;
  tags: string[];
  featured?: boolean;
  urgent?: boolean;
  companyLogo?: string;
  logo?: string;
  // Optional cover image for job cards, separate from company logo
  coverImageUrl?: string | null;
  source?: 'online' | 'newspaper';
  publishedDate: string;
  approvalStatus?: 'pending' | 'approved' | 'rejected';
  approvedBy?: string;
  approvedDate?: string;
  rejectedBy?: string;
  rejectedDate?: string;
  rejectionReason?: string;
  submittedBy?: string;
  submittedDate?: string;
}

export const mockJobs: Job[] = [
  // MegaJob Tier (6 jobs) - Premium companies with highest salaries
  {
    id: '1',
    title: 'Senior Software Engineer',
    company: 'TechCorp Nepal',
    location: 'Kathmandu',
    description: 'We are looking for a senior software engineer to join our dynamic team and lead innovative projects.',
    requirements: ['5+ years experience', 'React', 'Node.js', 'TypeScript'],
    postedDate: '2024-01-15',
    publishedDate: '2024-01-15',
    deadline: '2024-02-15',
    salary: 'NPR 80,000 - 120,000',
    type: 'mega_job',
    tier: 'megajob',
    category: 'Information Technology',
    experience: 'Senior Level',
    tags: ['Remote', 'Full-time'],
    featured: true,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=48&h=48&fit=crop&crop=center',
    approvalStatus: 'approved',
    approvedBy: 'admin',
    approvedDate: '2024-01-15'
  },
  {
    id: '2',
    title: 'Senior Product Manager',
    company: 'Google',
    location: 'Kathmandu',
    description: 'Lead product strategy and development for Google\'s emerging markets initiatives.',
    requirements: ['8+ years product management', 'Tech background', 'Analytics expertise', 'Leadership skills'],
    postedDate: '2024-01-19',
    publishedDate: '2024-01-19',
    deadline: '2024-02-19',
    salary: 'NPR 180,000 - 250,000',
    type: 'mega_job',
    tier: 'megajob',
    category: 'Product Management',
    experience: 'Senior Level',
    tags: ['Tech', 'Leadership'],
    featured: true,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '7',
    title: 'Chief Technology Officer',
    company: 'Microsoft',
    location: 'Kathmandu',
    description: 'Lead Microsoft\'s technology strategy and innovation initiatives in South Asia region.',
    requirements: ['15+ years tech leadership', 'Strategic planning', 'Team management', 'Cloud technologies', 'AI/ML expertise'],
    postedDate: '2024-01-20',
    publishedDate: '2024-01-20',
    deadline: '2024-03-20',
    salary: 'NPR 300,000 - 500,000',
    type: 'mega_job',
    tier: 'megajob',
    category: 'Executive Leadership',
    experience: 'Executive Level',
    tags: ['Executive', 'Leadership', 'Strategy'],
    featured: true,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1633409361618-c73427e4e206?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '8',
    title: 'Senior Data Scientist',
    company: 'Amazon',
    location: 'Kathmandu',
    description: 'Drive data-driven decision making and build machine learning models for Amazon\'s e-commerce platform.',
    requirements: ['PhD in Data Science/Statistics', '7+ years ML experience', 'Python/R', 'AWS', 'Deep Learning'],
    postedDate: '2024-01-21',
    publishedDate: '2024-01-21',
    deadline: '2024-02-21',
    salary: 'NPR 200,000 - 300,000',
    type: 'mega_job',
    tier: 'megajob',
    category: 'Data Science',
    experience: 'Senior Level',
    tags: ['AI/ML', 'Data Science', 'Remote'],
    featured: true,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '9',
    title: 'Senior DevOps Engineer',
    company: 'Netflix',
    location: 'Kathmandu',
    description: 'Scale Netflix\'s global streaming infrastructure and ensure 99.99% uptime for millions of users.',
    requirements: ['6+ years DevOps', 'Kubernetes', 'AWS/GCP', 'Terraform', 'Monitoring tools', 'CI/CD'],
    postedDate: '2024-01-22',
    publishedDate: '2024-01-22',
    deadline: '2024-02-22',
    salary: 'NPR 150,000 - 220,000',
    type: 'mega_job',
    tier: 'megajob',
    category: 'DevOps',
    experience: 'Senior Level',
    tags: ['DevOps', 'Cloud', 'Infrastructure'],
    featured: true,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '10',
    title: 'Senior Security Architect',
    company: 'Meta',
    location: 'Kathmandu',
    description: 'Design and implement security architecture for Meta\'s social media platforms serving billions of users.',
    requirements: ['8+ years cybersecurity', 'Security architecture', 'Threat modeling', 'Compliance', 'Risk assessment'],
    postedDate: '2024-01-23',
    publishedDate: '2024-01-23',
    deadline: '2024-02-23',
    salary: 'NPR 180,000 - 280,000',
    type: 'mega_job',
    tier: 'megajob',
    category: 'Cybersecurity',
    experience: 'Senior Level',
    tags: ['Security', 'Architecture', 'Compliance'],
    featured: true,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=48&h=48&fit=crop&crop=center'
  },

  // Premium Jobs (6 jobs) - Established companies with good salaries
  {
    id: '3',
    title: 'Full Stack Developer',
    company: 'Digital Innovation Hub',
    location: 'Kathmandu',
    description: 'Join our team to build cutting-edge web applications using modern technologies.',
    requirements: ['3+ years experience', 'React', 'Python/Django', 'PostgreSQL'],
    postedDate: '2024-01-16',
    publishedDate: '2024-01-16',
    deadline: '2024-02-16',
    salary: 'NPR 60,000 - 90,000',
    type: 'premium_job',
    tier: 'premium',
    category: 'Information Technology',
    experience: 'Mid Level',
    tags: ['Hybrid', 'Full-time'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '4',
    title: 'UX Design Lead',
    company: 'Apple',
    location: 'Kathmandu',
    description: 'Lead user experience design for Apple\'s emerging market products and services.',
    requirements: ['5+ years UX design', 'Design leadership', 'Prototyping tools', 'User research'],
    postedDate: '2024-01-19',
    publishedDate: '2024-01-19',
    deadline: '2024-02-19',
    salary: 'NPR 120,000 - 180,000',
    type: 'premium_job',
    tier: 'premium',
    category: 'Design',
    experience: 'Senior Level',
    tags: ['UX', 'Design'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '11',
    title: 'Backend Developer',
    company: 'Spotify',
    location: 'Kathmandu',
    description: 'Build scalable backend systems for Spotify\'s music streaming platform.',
    requirements: ['4+ years backend development', 'Java/Kotlin', 'Microservices', 'Kafka', 'Redis'],
    postedDate: '2024-01-24',
    publishedDate: '2024-01-24',
    deadline: '2024-02-24',
    salary: 'NPR 80,000 - 120,000',
    type: 'premium_job',
    tier: 'premium',
    category: 'Backend Development',
    experience: 'Mid Level',
    tags: ['Backend', 'Microservices', 'Streaming'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '12',
    title: 'Mobile App Developer',
    company: 'Uber',
    location: 'Kathmandu',
    description: 'Develop and maintain Uber\'s mobile applications for riders and drivers.',
    requirements: ['3+ years mobile development', 'React Native/Flutter', 'iOS/Android', 'API integration'],
    postedDate: '2024-01-25',
    publishedDate: '2024-01-25',
    deadline: '2024-02-25',
    salary: 'NPR 70,000 - 110,000',
    type: 'premium_job',
    tier: 'premium',
    category: 'Mobile Development',
    experience: 'Mid Level',
    tags: ['Mobile', 'React Native', 'Cross-platform'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '13',
    title: 'Cloud Solutions Architect',
    company: 'Salesforce',
    location: 'Kathmandu',
    description: 'Design cloud-native solutions and help enterprises migrate to Salesforce platform.',
    requirements: ['5+ years cloud architecture', 'Salesforce certified', 'AWS/Azure', 'Solution design'],
    postedDate: '2024-01-26',
    publishedDate: '2024-01-26',
    deadline: '2024-02-26',
    salary: 'NPR 100,000 - 150,000',
    type: 'premium_job',
    tier: 'premium',
    category: 'Cloud Architecture',
    experience: 'Senior Level',
    tags: ['Cloud', 'Salesforce', 'Architecture'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '14',
    title: 'Frontend Developer',
    company: 'Airbnb',
    location: 'Kathmandu',
    description: 'Create beautiful and responsive user interfaces for Airbnb\'s booking platform.',
    requirements: ['3+ years frontend development', 'React/Vue.js', 'TypeScript', 'CSS/SASS', 'Testing'],
    postedDate: '2024-01-27',
    publishedDate: '2024-01-27',
    deadline: '2024-02-27',
    salary: 'NPR 65,000 - 95,000',
    type: 'premium_job',
    tier: 'premium',
    category: 'Frontend Development',
    experience: 'Mid Level',
    tags: ['Frontend', 'React', 'UI/UX'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=48&h=48&fit=crop&crop=center'
  },

  // Prime Jobs (6 jobs) - Growing companies and entry-level positions
  {
    id: '5',
    title: 'Junior Software Developer',
    company: 'StartUp Tech',
    location: 'Kathmandu',
    description: 'Great opportunity for fresh graduates to start their career in software development.',
    requirements: ['0-2 years experience', 'Basic programming knowledge', 'JavaScript/Python', 'Eagerness to learn'],
    postedDate: '2024-01-17',
    publishedDate: '2024-01-17',
    deadline: '2024-02-17',
    salary: 'NPR 35,000 - 50,000',
    type: 'prime_job',
    tier: 'prime',
    category: 'Information Technology',
    experience: 'Entry Level',
    tags: ['Entry Level', 'Full-time'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '6',
    title: 'Junior Software Engineer',
    company: 'Tesla',
    location: 'Kathmandu',
    description: 'Join Tesla\'s software team to develop innovative automotive technologies.',
    requirements: ['Computer Science degree', 'Python/C++', 'Problem solving', 'Team collaboration'],
    postedDate: '2024-01-19',
    publishedDate: '2024-01-19',
    deadline: '2024-02-19',
    salary: 'NPR 55,000 - 80,000',
    type: 'prime_job',
    tier: 'prime',
    category: 'Automotive Software',
    experience: 'Entry Level',
    tags: ['Automotive', 'Software'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '15',
    title: 'Web Developer',
    company: 'Local Tech Solutions',
    location: 'Pokhara',
    description: 'Develop and maintain websites for local businesses and organizations.',
    requirements: ['1-3 years experience', 'HTML/CSS/JavaScript', 'WordPress', 'PHP', 'MySQL'],
    postedDate: '2024-01-28',
    publishedDate: '2024-01-28',
    deadline: '2024-02-28',
    salary: 'NPR 40,000 - 60,000',
    type: 'prime_job',
    tier: 'prime',
    category: 'Web Development',
    experience: 'Entry Level',
    tags: ['Web Development', 'WordPress', 'Local'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '16',
    title: 'Digital Marketing Specialist',
    company: 'Growth Marketing Agency',
    location: 'Kathmandu',
    description: 'Help businesses grow their online presence through digital marketing strategies.',
    requirements: ['2+ years digital marketing', 'Google Ads', 'Facebook Ads', 'SEO/SEM', 'Analytics'],
    postedDate: '2024-01-29',
    publishedDate: '2024-01-29',
    deadline: '2024-02-29',
    salary: 'NPR 45,000 - 70,000',
    type: 'prime_job',
    tier: 'prime',
    category: 'Digital Marketing',
    experience: 'Mid Level',
    tags: ['Marketing', 'SEO', 'Social Media'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '17',
    title: 'QA Engineer',
    company: 'Quality Assurance Pro',
    location: 'Kathmandu',
    description: 'Ensure software quality through comprehensive testing and automation.',
    requirements: ['2+ years QA experience', 'Manual testing', 'Automation tools', 'Bug tracking', 'Test planning'],
    postedDate: '2024-01-30',
    publishedDate: '2024-01-30',
    deadline: '2024-03-01',
    salary: 'NPR 50,000 - 75,000',
    type: 'prime_job',
    tier: 'prime',
    category: 'Quality Assurance',
    experience: 'Mid Level',
    tags: ['QA', 'Testing', 'Automation'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '18',
    title: 'UI/UX Designer',
    company: 'Creative Design Studio',
    location: 'Kathmandu',
    description: 'Create intuitive and beautiful user interfaces for web and mobile applications.',
    requirements: ['2+ years design experience', 'Figma/Sketch', 'Prototyping', 'User research', 'Design systems'],
    postedDate: '2024-01-31',
    publishedDate: '2024-01-31',
    deadline: '2024-03-02',
    salary: 'NPR 45,000 - 65,000',
    type: 'prime_job',
    tier: 'prime',
    category: 'UI/UX Design',
    experience: 'Mid Level',
    tags: ['Design', 'UI/UX', 'Figma'],
    featured: false,
    source: 'online',
    logo: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=48&h=48&fit=crop&crop=center'
  },

  // Newspaper Jobs (6 jobs) - Traditional job postings from newspapers
  {
    id: '19',
    title: 'Accountant',
    company: 'Himalayan Bank',
    location: 'Kathmandu',
    description: 'Handle financial records, prepare reports, and ensure compliance with banking regulations.',
    requirements: ['Bachelor in Accounting/Finance', '3+ years banking experience', 'Knowledge of banking software', 'Attention to detail'],
    postedDate: '2024-02-01',
    publishedDate: '2024-02-01',
    deadline: '2024-03-01',
    salary: 'NPR 50,000 - 70,000',
    type: 'newspaper_job',
    tier: 'newspaper',
    category: 'Banking & Finance',
    experience: 'Mid Level',
    tags: ['Banking', 'Finance', 'Accounting'],
    featured: false,
    source: 'newspaper',
    logo: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '20',
    title: 'Civil Engineer',
    company: 'Nepal Construction Company',
    location: 'Kathmandu',
    description: 'Oversee construction projects and ensure structural integrity of buildings and infrastructure.',
    requirements: ['Bachelor in Civil Engineering', '5+ years construction experience', 'Project management', 'AutoCAD knowledge'],
    postedDate: '2024-02-02',
    publishedDate: '2024-02-02',
    deadline: '2024-03-02',
    salary: 'NPR 60,000 - 90,000',
    type: 'newspaper_job',
    tier: 'newspaper',
    category: 'Engineering',
    experience: 'Senior Level',
    tags: ['Civil Engineering', 'Construction', 'Project Management'],
    featured: false,
    source: 'newspaper',
    logo: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '21',
    title: 'Teacher - Secondary Level',
    company: 'Kathmandu Model School',
    location: 'Kathmandu',
    description: 'Teach mathematics and science subjects to secondary level students.',
    requirements: ['Bachelor in Education', 'Teaching license', '2+ years teaching experience', 'Good communication skills'],
    postedDate: '2024-02-03',
    publishedDate: '2024-02-03',
    deadline: '2024-03-03',
    salary: 'NPR 35,000 - 50,000',
    type: 'newspaper_job',
    tier: 'newspaper',
    category: 'Education',
    experience: 'Mid Level',
    tags: ['Teaching', 'Education', 'Mathematics'],
    featured: false,
    source: 'newspaper',
    logo: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '22',
    title: 'Nurse',
    company: 'Tribhuvan University Teaching Hospital',
    location: 'Kathmandu',
    description: 'Provide patient care and assist doctors in medical procedures.',
    requirements: ['Bachelor in Nursing', 'Nursing license', '1+ years hospital experience', 'Compassionate care'],
    postedDate: '2024-02-04',
    publishedDate: '2024-02-04',
    deadline: '2024-03-04',
    salary: 'NPR 40,000 - 60,000',
    type: 'newspaper_job',
    tier: 'newspaper',
    category: 'Healthcare',
    experience: 'Entry Level',
    tags: ['Healthcare', 'Nursing', 'Patient Care'],
    featured: false,
    source: 'newspaper',
    logo: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '23',
    title: 'Sales Manager',
    company: 'Chaudhary Group',
    location: 'Kathmandu',
    description: 'Lead sales team and develop strategies to increase revenue and market share.',
    requirements: ['Bachelor in Business/Marketing', '5+ years sales experience', 'Team leadership', 'Market analysis'],
    postedDate: '2024-02-05',
    publishedDate: '2024-02-05',
    deadline: '2024-03-05',
    salary: 'NPR 70,000 - 100,000',
    type: 'newspaper_job',
    tier: 'newspaper',
    category: 'Sales & Marketing',
    experience: 'Senior Level',
    tags: ['Sales', 'Management', 'Leadership'],
    featured: false,
    source: 'newspaper',
    logo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=48&h=48&fit=crop&crop=center'
  },
  {
    id: '24',
    title: 'Administrative Officer',
    company: 'Government of Nepal',
    location: 'Kathmandu',
    description: 'Handle administrative tasks and coordinate between different government departments.',
    requirements: ['Bachelor degree', 'Government exam passed', '3+ years admin experience', 'Documentation skills'],
    postedDate: '2024-02-06',
    publishedDate: '2024-02-06',
    deadline: '2024-03-06',
    salary: 'NPR 45,000 - 65,000',
    type: 'newspaper_job',
    tier: 'newspaper',
    category: 'Government',
    experience: 'Mid Level',
    tags: ['Government', 'Administration', 'Public Service'],
    featured: false,
    source: 'newspaper',
    logo: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=48&h=48&fit=crop&crop=center'
  }
];

// Export categories and companies from the jobs
export const mockCategories = [
  { id: '1', name: 'Information Technology', description: 'Software development, IT services, and technology roles' },
  { id: '2', name: 'Product Management', description: 'Product strategy, development, and management roles' },
  { id: '3', name: 'Design', description: 'UI/UX design, product design, and creative roles' },
  { id: '4', name: 'Automotive Software', description: 'Software development for automotive industry' }
];

export const mockCompanies = [
  { id: '1', name: 'TechCorp Nepal', industry: 'Technology', size: '100-500', location: 'Kathmandu', verified: true },
  { id: '2', name: 'Google', industry: 'Technology', size: '10000+', location: 'Kathmandu', verified: true },
  { id: '3', name: 'Digital Innovation Hub', industry: 'Technology', size: '50-100', location: 'Kathmandu', verified: true },
  { id: '4', name: 'Apple', industry: 'Technology', size: '10000+', location: 'Kathmandu', verified: true },
  { id: '5', name: 'StartUp Tech', industry: 'Technology', size: '10-50', location: 'Kathmandu', verified: true },
  { id: '6', name: 'Tesla', industry: 'Automotive', size: '1000-10000', location: 'Kathmandu', verified: true }
];

